// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Project struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Text    string  `json:"text"`
	Created string  `json:"created"`
	Tasks   []*Task `json:"tasks"`
}

type ProjectInput struct {
	Name string `json:"name"`
	Text string `json:"text"`
}

type Task struct {
	ID        string   `json:"id"`
	Project   *Project `json:"project"`
	ProjectID string   `json:"project_id"`
	Name      string   `json:"name"`
	Text      string   `json:"text"`
	Created   string   `json:"created"`
}

type TaskInput struct {
	ProjectID string `json:"project_id"`
	Name      string `json:"name"`
	Text      string `json:"text"`
}
