import Head from "next/head";
import { useEffect } from "react";

import { Nav } from "./../components";
import Dashboard from "./dashboard";

import { ToastContainer, toast, cssTransition } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";

import { ArrowTopRightOnSquareIcon } from "@heroicons/react/24/solid";

import { successToast, warningToast } from "../utils/toast";

//animations.css
const toastTransition = cssTransition({
    enter: "toast-enter",
    exit: "toast-exit",
});

import NotificationStore from "../store/notifications";
import GPHTEST from '../components/gphtest';
import Guest from "./guest";

export default function App({ countries }: any) {
    const [addNotification] = NotificationStore((state) => [state.addNotification]);

    useEffect(() => {
        if (
            localStorage.theme === "dark" ||
            (!("theme" in localStorage) &&
                window.matchMedia("(prefers-color-scheme: dark)").matches)
        ) {
            document.documentElement.classList.add("dark");
        } else {
            document.documentElement.classList.remove("dark");
        }

        toast(
            <a href="">You have a new assignment</a>
            ,
            {
                icon: <ArrowTopRightOnSquareIcon />,
                onClose: () => addNotification({ id: 0, sender: "system", status: "warning", text: "test" }),
                ...warningToast
            }
        );
    }, []);



    return (
        <>
            <Head>
                <title>OctoManage</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-row bg-black w-screen h-screen">
                {/* <ToastContainer
                    transition={toastTransition}
                    className={"mt-10 mr-1 z-10 select-none"}
                    position="top-right"
                    closeOnClick={false}
                    draggable={true}
                    closeButton={false}
                    toastClassName={"border border-neutral-800"}
                    theme="dark"
                />
                <Nav />
                <GPHTEST/> */}
                <Guest />

            </div>
        </>
    );
}



